# Generated by Django 5.2.1 on 2026-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_id", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
