# Generated by Django 5.2.1 on 2026-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtrack",
            name="ip_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emailtrack",
            name="open_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="emailtrack",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailtrack",
            name="tracking_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
