# Generated by Django 5.2.1 on 2026-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_emailtrack_ip_address_emailtrack_open_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtrack",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailtrack",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
